# IG 6th Silly Sentences
name1 = input("what is your name")
name = input(" give me a name")
print("thank you")
food = input("give me a food")
print("thank you")
body_part = input("give me a body part")
print("thank you")
place = input("give me a place")
print("thank you")
animal = input("give me an animal")
print("thank you")  
print("my evil babysiter", name , "had gave me moldy", food , "so i took a bite and i fouund a hairy" , body_part,"so i ran to" , place ," and fought a" , animal ,"with my bare hands")
print("thank you for playing my game" , name ,)